# Generated by Django 2.2.4 on 2019-08-25 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190824_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='location',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_place_id',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(default='null', srid=4326),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
